GET http://localhost:5000
Accept: application/json 

###
GET http://localhost:5000/getDraftGroup/NBA
Accept: application/json 

###

GET http://localhost:5000/getDraftGroup/WNBA
Accept: application/json 

###

POST http://localhost:5000/getEdittableCSV
Content-Type: application/json 

{
    "sportName" : "NBA",
    "season" : "2022-23",
    "perMode" : "PerGame",
    "seasonType" : "Playoffs",
    "draftGroup" : 87852
}

###

POST http://localhost:5000/getEdittableCSV
Content-Type: application/json 

{
    "sportName" : "NBA",
    "season" : 2023,
    "perMode" : "PerGame",
    "seasonType" : "Regular+Season",
    "draftGroup" : 87708,
    "realSport" : "WNBA"
}